openapi: 3.1.0
info:
  version: 1.0.0
  title: Questionnaire app #назва вашого додатку
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: This is a documentation of Questionnaire app #опис вашого додатку
tags:
  # теги, що ви будете використовувати
  - name: Questionnaires
    description: Operations with Questionnaires
  - name: Responses
    description: Responses operations
servers:
  - url: relaxed-phylis/questionnaire-api
  - url: http://127.0.0.1:8080
paths:
  # тут будуть посилання на ендпоінти
  /questionnaires:
    get:
      $ref: ../swagger/paths/questionnaires/get.yaml
    post:
      $ref: ../swagger/paths/questionnaires/post.yaml
  /questionnaires/{id}:
    get:
      $ref: ../swagger/paths/questionnaires/{id}/get.yaml
    delete:
      $ref: ../swagger/paths/questionnaires/{id}/delete.yaml
    patch:
      $ref: ../swagger/paths/questionnaires/{id}/patch.yaml
  /responses:
    post:
      $ref: ../swagger/paths/responses/post.yaml
  /responses/{id}:
    get:
      $ref: ../swagger/paths/responses/{id}/get.yaml
components:
  securitySchemes: {}
